INSERT INTO filos (descricao,folhas_verdadeiras,caule_verdadeiro,raiz_verdadeiras,frutos,flores,sementes,ativo) VALUES
	 ('ANGIOSPERMA',true,true,true,true,true,true,true),
	 ('BRIOFITA',false,false,false,false,false,false,true),
	 ('GIMNOSPERMA',true,true,true,false,false,true,true),
	 ('PTERIDOFITA',true,true,true,false,false,false,true);
INSERT INTO classes (descricao,id_filo,ativo) VALUES
	 ('EUDICOTILEDONEAS',1,true),
	 ('MONOCOTILEDONEAS',1,true),
	 ('ANTHOCEROPHYTA',2,true),
	 ('BRYOPHYTA',2,true),
	 ('MARCHANTIOPHYTA',2,true),
	 ('CONIFERAS',3,true),
	 ('CICADOFITAS',3,true),
	 ('GNETOPHYTA',3,true),
	 ('GINKGOPHYTA',3,true),
	 ('MONILOPHYTA',4,true),
	 ('LYCOPODIOPHYTA',4,true);
INSERT INTO ordens (descricao,classe_id,ativo) VALUES
	 ('ASTERACEAE',1,true),
	 ('LEGUMINOSA',1,true),
	 ('ROSACEAS',1,true),
	 ('ANTOCEROS',3,true),
	 ('MUSGOS',4,true),
	 ('HEPATICA',5,true),
	 ('CYCADACEAE',7,true),
	 ('ZAMIACEAE',7,true),
	 ('STANGERIACEAE',7,true),
	 ('WELWITSCHIALES',8,true),
	 ('EPHEDRALES',8,true),
	 ('GNETALES',8,true),
	 ('LICOPODIOS',11,true),
	 ('ISOETES',11,true),
	 ('SELAGINELLAS',11,true),
	 ('SEM ORDEM',2,true),
	 ('SEM ORDEM',6,true),
	 ('SEM ORDEM',9,true),
	 ('SEM ORDEM',10,true);	 
INSERT INTO raizes (descricao,classe_id,ativo) VALUES
	 ('RIZOIDES',3,true),
	 ('RIZOIDES',4,true),
	 ('RIZOIDES',5,true),
	 ('ADVENTICIAS',11,true),
	 ('ENDOGENAS',10,true),
	 ('FASCICULADA',2,true),
	 ('PIVOTANTE',1,true),
	 ('AXIAL',6,true),
	 ('AXIAL',7,true),
	 ('AXIAL',8,true),
	 ('AXIAL',9,true);
INSERT INTO caules (descricao,classe_id,ativo) VALUES
	 ('CAULOIDE',3,true),
	 ('CAULOIDE',4,true),
	 ('CAULOIDE',5,true),
	 ('ESPORIFEROS',10,true),
	 ('RAMOSO',11,true),
	 ('DESORDENADO',2,true),
	 ('CILINDRICO',1,true),
	 ('LENHOSO',6,true),
	 ('LENHOSO',7,true),
	 ('LENHOSO',8,true),
	 ('LENHOSO',9,true);
INSERT INTO folhagens (descricao,classe_id,ativo) VALUES
	 ('PARALELINERVEA',2,true),
	 ('RETICULADA',1,true),
	 ('FILOIDES',3,true),
	 ('FILOIDES',4,true),
	 ('FILOIDES',5,true),
	 ('LOBULADO',9,true),
	 ('CORIACEAS',7,true),
	 ('ACICULAR',6,true),
	 ('SIMPLES',8,true),
	 (' NERVURAS SECUNDARIAS',10,true),
	 ('COMPLEXAS',11,true);
INSERT INTO plantas (nome,cor,filo_id,classe_id,ordem_id,raiz_id,caule_id,folhagem_id,ativo) VALUES
     ('SAMAMBAIA','VERDE ESCURO',3,6,17,8,8,8,true),
	 ('GIRASSOL','AMARELA',1,1,1,2,5,5,true),
	 ('BANANEIRA','AMARELA',1,2,16,1,4,4,true),
	 ('DASMAQUEIRO','VERMELHA',1,1,3,2,5,5,true),
	 ('PLANTA DETALHAR','VERDE',1,1,1,7,7,2,true),
	 ('PLANTA EXCLUIR','VERDE',1,1,1,7,7,2,true),
	 ('PLANTA ATUALIZAR','CASTANHO',4,10,19,5,4,10,true);